---
title: Meredith Overmyer Portfolio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Meredith Overmyer
keywords: Meredith Overmyer
favicon: img/favicon.ico
markdown: kramdown
permalink: "/:title"
gems:
- jekyll-sitemap
